{{- if and (not .Values.db.connectionString) .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workingcalendar.fullname" . }}-postgres
  labels:
    {{- include "workingcalendar.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "workingcalendar.fullname" . }}-postgres
  type: ClusterIP
{{- end }}
