{{- if and (not .Values.db.connectionString) .Values.postgres.enabled .Values.postgres.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workingcalendar.fullname" . }}-db
  labels:
    {{- include "workingcalendar.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgres.auth.username | b64enc | quote }}
  password: {{ .Values.postgres.auth.password | b64enc | quote }}
  connectionString: {{ printf "Host=%s-postgres;Port=5432;Database=workingcalendar;Username=%s;Password=%s" (include "workingcalendar.fullname" .) .Values.postgres.auth.username .Values.postgres.auth.password | b64enc | quote }}
{{- end }}
