apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: workingcalendar
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yellow444@email.ru
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
