apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: workingcalendar
  name: pgdata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Mi
status: {}
