apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
#  hostPath:
#    path: "/mnt/data/pv2"
  local:
    path: "/mnt/local-storage/pv2"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - master
            - worker
